nodeLinker: node-modules

plugins:
  - checksum: ed8dadb66df330241a321bd0bac88ce7177abb39b56a0992a1475c0b8ceef01672e04049b1cda856645b1ebf7e30d5d77973a196cab3ec1105395a3f33f88780
    path: .yarn/plugins/@yarnpkg/plugin-catalogs.cjs
    spec: "https://raw.githubusercontent.com/toss/yarn-plugin-catalogs/main/bundles/%40yarnpkg/plugin-catalogs.js"

yarnPath: .yarn/releases/yarn-4.9.3.cjs

catalogs:
  list:
    "@types/jest": 30.0.0
    "@types/node": 24.3.0
    "eslint": 9.33.0
    "prettier": 3.6.2
    "tsup": 8.5.0
    "typescript": 5.9.2
    "jest": 30.0.5
    "ts-jest": 29.4.1
    "rimraf": 6.0.1